### ISSUE TITLE
Always return the same instance from plain option's createNone()

### ISSUE THREAD

**Issue by jraoult** [karen-irc/option-t#774] opened 2020-11-13 14:39 UTC
Plain option's `createNone` always return the same structurally equivalent value. This returned value is also immutable (both properties are `readonly`). Based on this, I think there is an opportunity to always return the same `None` instance.

There is a potential minor gain in reducing allocation (although JS engines these days are pretty good a dealing with this) but I'm actually interested in this for caching purposes. When using an `Option` as a key for a cache, it is not possible to use identity comparison and is therefore forcing me to use structural test. If the `None` instance is constant, I can optimise the test for it by using an identity check.

Would you consider this?

**Comment by tetsuharuohzeki** [comment] 2020-11-15 15:29
It sounds like a better approach for performance but I'm hesitating to do your proposed optimization for a long time....
To be honest, I summarize my thought to "we can do it but we don't have any reason to do it without actual benchmark result".

My thought is here:

1. We should do this kind of optimizations by a benchmark result.
    - We need add a benchmark to measure this optimization in both micro benchmark level and real application level.
        - I bet this optimization would improve in the micro benchmark, but I'm not sure about that whether macro (real application) benchmark would also improve the score. We must measure it.
        - Modern JIT compiler do bunch of optimizations including loop-invariant code motion and object allocation sinking. We can only trust the result of real application benchmark result.
    - In the past, [rxjs tried to cache the error object](https://github.com/ReactiveX/rxjs/blob/7004c2630aa6c3d521068d2a4b43d86c8c45e8da/src/util/tryCatch.ts) but its approach is not valuable for performance and [rxjs removed it](https://github.com/ReactiveX/rxjs/pull/1251). Of course, this is the tale in some years ago, the situation would be changed. But I hesitate to do this without benchmarks. Performance optimization is complex.
1. This optimization change the API semantics.
    - I believe almost (~99%) user code would not do that, but some code depends on the behavior which is that `createNone` returns a new object. I believe strongly that every user did not do that (repeatedly). But we need be careful to change it.
    - In a semantic level, I think it would not be a big problem if we can change to return the same cached object. Because:
        - This is a problem just by history and technical debt.
        - `null === null` be `true`. We can same do thing.
        - other APIs e.g. `map()` returns same object if the input is `None`.
1. With a hat of a user of this project, I'm not sure about that how many people do have a problem about the performance caused by that we don't do this optimization. 
    - `Option<T>` in `PlainOption` is a bit incomplete type, I think. It can use it as a convinient type which has some compatibility with `Result<T, E>`. But I think we don't have a strong reason to keep to use `Option<T>` and we tend to replace it with `Nullable<T>` or `Undefinable<T>`.
    - In a performance senstive path,  we would do optimize an application code aggressively. Then I suspect we would not use this object in that case because `Option<T>` ca be replaceable to `Nullable<T>`.

**Comment by tetsuharuohzeki** [comment] 2020-11-15 16:20
>  To be honest, I summarize my thought to "we can do it but we don't have any reason to do it without actual benchmark result".


Additionally, I think this kind of design change is hard problem as a library providing a fundamental type and utilities.
Some performance optimization may improve a performance for _application A_, but may cause a regression for _application B_. Then we need to take a hard decision. Thus I'm hesitating to do this for a long time and continue to take an conservative approach which returns a new object every time.

This "conservative" design has these aspects:

1. This design make a code simple.
1. This design can also keep a consitent behavior with `createErr()`.
1. Fortunately, `Option<T>` is simple type and  `createNone()` in `PlainOption` is easy to reimplement the version which has a internally cache mechanism by userland.
1. Fortunately, `Option<T>` is replacable with `Nullable<T>` or `Undefinable<T>` in practice excluding the case is that user code aims to share a caller code with the variants of `Result<T, E>`. 

I wrote "we can do it" in the above but I think this design change would take a  long time to decide to accept even if the benchmark score is fine. We may require benchmarks for various workload.

**Comment by jraoult** [comment] 2020-11-15 20:18
> But I think we don't have a strong reason to keep to use Option<T> and we tend to replace it with Nullable<T> or Undefinable<T>.
Yeah I was wondering if I should stop using it and just use `null` and some helper function instead, so that I can use identity comparison on the _empty_ case. I think this is the right solution.

**Comment by tetsuharuohzeki** [comment] 2021-02-13 17:01
I close this once as wontfix

**Closed by tetsuharuohzeki** 2021-02-13 17:01 UTC
Labels: A-optimization, B-RFC, I-breaking change, I-perf
